# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c70534ddb6368d90d4f551a8a076e8e33fc336da382e3cc1f143b15efa8cb06aac4c1a12ac8cce90ec0dae2f8d070cd33da40aabc03154115fe2c45ccd592a78

test:
  secret_key_base: ca78a1dfd82defb4e76e4d817866ae92f84616741b871713921a595492fee87b1797e283d5d88929467d84337c7ebc5c5067473e19ac663c723d0409ccaa1fb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
